#!/usr/bin/env python3
"""
Synthetic Development Fixtures Generator for IPsec VPN Analyzer.

IMPORTANT RESEARCH NOTICE:
Captures generated by this script are SYNTHETIC DEVELOPMENT FIXTURES strictly for parser testing.
They MUST NOT be used or labeled as real experimental ground truth.
Real ground truth captures belong exclusively in data/pcaps/real/ produced by strongSwan on Linux.
"""

import os
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

# Disable sandbox-restricted DNS resolv reading before importing scapy layers
os.environ["SCAPY_USE_NETIFACES"] = "0"
try:
    from scapy.config import conf
    conf.read_resolv_conf = False
except Exception:
    pass

try:
    from scapy.all import IP, UDP, Raw, wrpcap
    from scapy.layers.isakmp import ISAKMP
except ImportError as e:
    print(f"Error importing Scapy: {e}")
    sys.exit(1)


SYNTHETIC_DIR = PROJECT_ROOT / "data" / "pcaps" / "synthetic"
SYNTHETIC_DIR.mkdir(parents=True, exist_ok=True)


def create_synthetic_ike_sa_init():
    """Generates synthetic binary IKE_SA_INIT packet header (IKEv2, version 0x20) for parser fixture."""
    init_spi = os.urandom(8)
    resp_spi = b"\x00" * 8
    
    # Construct ISAKMP/IKE header (UDP port 500) for IKEv2 (version=0x20)
    isakmp_hdr = ISAKMP(
        init_cookie=init_spi,
        resp_cookie=resp_spi,
        next_payload=33, # Security Association Payload
        version=0x20,    # IKEv2 (Major 2, Minor 0)
        exch_type=34,    # IKE_SA_INIT
        flags=0x08,      # Initiator flag
        id=0
    )
    
    payload = Raw(load=b"\x00\x00\x00\x28\x00\x00\x00\x24\x01\x01\x00\x00" + b"\x00" * 24)
    pkt = IP(src="192.168.100.2", dst="192.168.100.3") / UDP(sport=500, dport=500) / isakmp_hdr / payload
    return pkt


def create_synthetic_esp_packet(spi=0x12345678, seq=1):
    """Generates synthetic binary ESP packet (IP protocol 50) fixture."""
    esp_header = Raw(load=spi.to_bytes(4, 'big') + seq.to_bytes(4, 'big') + os.urandom(64))
    pkt = IP(src="192.168.100.2", dst="192.168.100.3", proto=50) / esp_header
    return pkt


def generate_all_synthetic_fixtures():
    fixtures = [
        ("SYNTH-TEST-001.pcap", "Synthetic IKEv2 Tunnel AES-128 Development Fixture"),
        ("SYNTH-TEST-002.pcap", "Synthetic IKEv2 Tunnel AES-256-GCM Development Fixture"),
        ("SYNTH-TEST-003.pcap", "Synthetic IKEv2 Transport AES-128 Development Fixture"),
    ]

    print("Generating Synthetic Development Fixtures in data/pcaps/synthetic/...")
    
    for filename, label in fixtures:
        filepath = SYNTHETIC_DIR / filename
        packets = []
        
        # 1. Add synthetic IKE_SA_INIT negotiation frames (version=0x20)
        packets.append(create_synthetic_ike_sa_init())
        
        # 2. Add synthetic ESP encrypted traffic frames
        for seq in range(1, 11):
            packets.append(create_synthetic_esp_packet(spi=0x0a0b0c0d, seq=seq))
            
        wrpcap(str(filepath), packets)
        print(f"  [+] Created {filename} ({len(packets)} synthetic packets) - {label}")

    print("\nSynthetic Development Fixtures generation complete.")


if __name__ == "__main__":
    generate_all_synthetic_fixtures()
