# strongSwan swanctl configuration for Peer B (192.168.100.3)
# Defines experimental connection proposals for TEST-001, TEST-002, and TEST-003.

connections {
   test-001 {
      local_addrs  = 192.168.100.3
      remote_addrs = 192.168.100.2
      version = 2
      proposals = aes128-sha256-modp2048

      local {
         auth = psk
         id = peer-b@lab.test
      }
      remote {
         auth = psk
         id = peer-a@lab.test
      }
      children {
         test-001-sa {
            local_ts = 10.2.0.0/24
            remote_ts = 10.1.0.0/24
            mode = tunnel
            esp_proposals = aes128-sha256-modp2048
         }
      }
   }

   test-002 {
      local_addrs  = 192.168.100.3
      remote_addrs = 192.168.100.2
      version = 2
      proposals = aes256gcm16-prfsha256-ecp256

      local {
         auth = psk
         id = peer-b@lab.test
      }
      remote {
         auth = psk
         id = peer-a@lab.test
      }
      children {
         test-002-sa {
            local_ts = 10.2.0.0/24
            remote_ts = 10.1.0.0/24
            mode = tunnel
            esp_proposals = aes256gcm16-ecp256
         }
      }
   }

   test-003 {
      local_addrs  = 192.168.100.3
      remote_addrs = 192.168.100.2
      version = 2
      mobike = no
      proposals = aes128-sha384-modp2048

      local {
         auth = psk
         id = peer-b@lab.test
      }
      remote {
         auth = psk
         id = peer-a@lab.test
      }
      children {
         test-003-sa {
            local_ts = 192.168.100.3/32
            remote_ts = 192.168.100.2/32
            mode = transport
            esp_proposals = aes128-sha384-modp2048
         }
      }
   }

   test-004 {
      local_addrs  = 192.168.100.3
      remote_addrs = 192.168.100.2
      version = 2
      mobike = no
      proposals = aes256gcm16-prfsha384-ecp384

      local {
         auth = psk
         id = peer-b@lab.test
      }
      remote {
         auth = psk
         id = peer-a@lab.test
      }
      children {
         test-004-sa {
            local_ts = 192.168.100.3/32
            remote_ts = 192.168.100.2/32
            mode = transport
            esp_proposals = aes256gcm16-ecp384
         }
      }
   }

   test-005 {
      local_addrs  = 192.168.100.3
      remote_addrs = 192.168.100.2
      version = 2
      proposals = aes128-sha256-modp3072
      encap = yes

      local {
         auth = psk
         id = peer-b@lab.test
      }
      remote {
         auth = psk
         id = peer-a@lab.test
      }
      children {
         test-005-sa {
            local_ts = 10.2.0.0/24
            remote_ts = 10.1.0.0/24
            mode = tunnel
            esp_proposals = aes128-sha256-modp3072
         }
      }
   }
}

secrets {
   ike-peer-a {
      id-1 = peer-a@lab.test
      secret = "SIH-IPsec-Lab-Secret-2026!"
   }
}
